# Generated by Django 5.1.5 on 2025-02-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, unique=True)),
                ('quadrant', models.IntegerField()),
                ('ring', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('moved', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
